//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.View.Modules
{
    public partial class LeaveConfiguration
    {
        /// <summary>
        /// gvInlineConfig control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvInlineConfig;

        /// <summary>
        /// lblMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
