using System;

namespace DataObject
{
    public class EmployeeOnboardingDO
    {
        public int UserId { get; set; }
        public string EmployeeCode { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Gender { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public string Nationality { get; set; }
        public string EmploymentType { get; set; }
        public string EmployeeCategory { get; set; }
        public DateTime? JoiningDate { get; set; }
        public DateTime? ConfirmationDate { get; set; }
        public DateTime? ProbationEndDate { get; set; }
        public DateTime? RetirementDate { get; set; }
        public int ProbationMonths { get; set; }
        public string EmployeeStatus { get; set; }
        public int NoticePeriod { get; set; }
        public DateTime? ExitDate { get; set; }
        public string SeparationReason { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string BranchOffice { get; set; }
        public string Location { get; set; }
        public int ReportingManagerId { get; set; }
        public int FunctionalManagerId { get; set; }
        public int HodId { get; set; }
        public string Designation { get; set; }
        public string EmployeeLevel { get; set; }
        public string AttendanceType { get; set; }
        public string WeeklyOff { get; set; }
        public string WorkingHours { get; set; }
        public string AttendancePolicy { get; set; }
        public string PunchingDeviceId { get; set; }
        public string BiometricId { get; set; }
        public string OvertimeEligible { get; set; }
        public decimal OvertimeRate { get; set; }
        public string WorkLocation { get; set; }
        public string RemoteWorkAllowed { get; set; }
        public string SalaryStructure { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal Ctc { get; set; }
        public DateTime? SalaryEffectiveDate { get; set; }
        public string PaymentMode { get; set; }
        public string UanNumber { get; set; }
        public string PfNumber { get; set; }
        public string EsicNumber { get; set; }
        public string ProfessionalTaxNumber { get; set; }
        public string LabourWelfareFundNumber { get; set; }
        public string TaxRegime { get; set; }
        public string TdsApplicable { get; set; }
        public string AssetType { get; set; }
        public string AssetNumber { get; set; }
        public string AssetName { get; set; }
        public DateTime? AssignedDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public string AssetCondition { get; set; }
        public string AssetStatus { get; set; }
        public int InsertedBy { get; set; }
    }

    public class EmployeeOnboardingResponseDO
    {
        public string Status { get; set; }
        public string Message { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string AutoGeneratedPassword { get; set; }
    }

    public class EmployeeAssetDO
    {
        public string AssetType { get; set; }
        public string AssetNumber { get; set; }
        public string AssetName { get; set; }
        public DateTime? AssignedDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public string AssetCondition { get; set; }
        public string AssetStatus { get; set; }
    }
}
